name: Run Cron Job

on:
  push:
    branches:
    - main 
  schedule:
    - cron: "0 0 * * *"

jobs:
  send_post_request:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request
        env:
          API_ENDPOINT: "https://price-wice.vercel.app/api/cron/daily-check"
        run: |
          curl -X POST $API_ENDPOINT \
          -H "Content-Type: application/json" \